#lang rosette

(require rosette/lib/synthax)

(provide (all-defined-out))

; all the constants

(define CLAIM_CLAIMABLE_BALANCE_LINE_FULL -3)
(define LIQUIDITY_POOL_DEPOSIT_SUCCESS 0)
(define ENVELOPE_TYPE_SCPVALUE 4)
(define CREATE_CLAIMABLE_BALANCE_NOT_AUTHORIZED -4)
(define CLAIM_PREDICATE_UNCONDITIONAL 0)
(define ASSET_TYPE_CREDIT_ALPHANUM12 2)
(define CHANGE_TRUST_TRUST_LINE_MISSING -6)
(define txFAILED -1)
(define SET_OPTIONS 5)
(define CREATE_ACCOUNT_SUCCESS 0)
(define MANAGE_BUY_OFFER_LOW_RESERVE -12)
(define CREATE_CLAIMABLE_BALANCE_NO_TRUST -3)
(define PAYMENT_SRC_NOT_AUTHORIZED -4)
(define MANAGE_BUY_OFFER_UNDERFUNDED -7)
(define CREATE_ACCOUNT 0)
(define CREATE_ACCOUNT_LOW_RESERVE -3)
(define CREATE_CLAIMABLE_BALANCE_LOW_RESERVE -2)
(define CLAWBACK_NO_TRUST -3)
(define CHANGE_TRUST_MALFORMED -1)
(define CLAIM_ATOM_TYPE_ORDER_BOOK 1)
(define REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE -4)
(define CHANGE_TRUST_NO_ISSUER -2)
(define opTOO_MANY_SPONSORING -6)
(define SET_TRUST_LINE_FLAGS_SUCCESS 0)
(define PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER -9)
(define AUTH_IMMUTABLE_FLAG 4)
(define LIQUIDITY_POOL_CONSTANT_PRODUCT 0)
(define CLAWBACK_CLAIMABLE_BALANCE_NOT_CLAWBACK_ENABLED -3)
(define ENVELOPE_TYPE_AUTH 3)
(define CLAIM_CLAIMABLE_BALANCE 15)
(define CLAWBACK_NOT_CLAWBACK_ENABLED -2)
(define CHANGE_TRUST_SUCCESS 0)
(define CLAIM_CLAIMABLE_BALANCE_SUCCESS 0)
(define ACCOUNT_MERGE_SUCCESS 0)
(define PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED -2)
(define PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION -5)
(define ACCOUNT_MERGE_DEST_FULL -6)
(define ENVELOPE_TYPE_TX_V0 0)
(define SET_OPTIONS_SUCCESS 0)
(define ALLOW_TRUST_LOW_RESERVE -6)
(define MASK_ACCOUNT_FLAGS 7)
(define INFLATION_NOT_TIME -1)
(define CREATE_ACCOUNT_MALFORMED -1)
(define AUTHORIZED_TO_MAINTAIN_LIABILITIES_FLAG 2)
(define opINNER 0)
(define KEY_TYPE_MUXED_ED25519 256)
(define CLAIM_CLAIMABLE_BALANCE_NOT_AUTHORIZED -5)
(define MANAGE_BUY_OFFER_SELL_NOT_AUTHORIZED -4)
(define CLAIMANT_TYPE_V0 0)
(define SET_OPTIONS_INVALID_INFLATION -4)
(define MANAGE_BUY_OFFER_CROSS_SELF -8)
(define ACCOUNT_MERGE_NO_ACCOUNT -2)
(define ALLOW_TRUST_TRUST_NOT_REQUIRED -3)
(define PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF -11)
(define SET_OPTIONS_BAD_SIGNER -8)
(define CREATE_ACCOUNT_UNDERFUNDED -2)
(define REVOKE_SPONSORSHIP_LEDGER_ENTRY 0)
(define MANAGE_SELL_OFFER_BUY_NO_TRUST -3)
(define ACCOUNT_MERGE_MALFORMED -1)
(define SET_TRUST_LINE_FLAGS_LOW_RESERVE -5)
(define SET_OPTIONS_CANT_CHANGE -5)
(define MASK_CLAIMABLE_BALANCE_FLAGS 1)
(define SET_OPTIONS_INVALID_HOME_DOMAIN -9)
(define MASK_OFFERENTRY_FLAGS 1)
(define CLAWBACK_CLAIMABLE_BALANCE_NOT_ISSUER -2)
(define MANAGE_BUY_OFFER 12)
(define REVOKE_SPONSORSHIP_NOT_SPONSOR -2)
(define PAYMENT_UNDERFUNDED -2)
(define txNO_ACCOUNT -8)
(define MASK_ACCOUNT_FLAGS_V17 15)
(define TRUSTLINE 1)
(define PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS -10)
(define BUMP_SEQUENCE_BAD_SEQ -1)
(define PATH_PAYMENT_STRICT_RECEIVE 2)
(define PAYMENT_NOT_AUTHORIZED -7)
(define MANAGE_BUY_OFFER_NOT_FOUND -11)
(define CLAIM_PREDICATE_NOT 3)
(define MANAGE_BUY_OFFER_BUY_NO_TRUST -3)
(define ALLOW_TRUST_SUCCESS 0)
(define MANAGE_SELL_OFFER_BUY_NO_ISSUER -10)
(define MAX_SIGNERS 20)
(define opEXCEEDED_WORK_LIMIT -5)
(define SET_OPTIONS_LOW_RESERVE -1)
(define CREATE_CLAIMABLE_BALANCE_UNDERFUNDED -5)
(define CHANGE_TRUST 6)
(define PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST -6)
(define PATH_PAYMENT_STRICT_RECEIVE_SRC_NOT_AUTHORIZED -4)
(define MEMO_HASH 3)
(define ENVELOPE_TYPE_OP_ID 6)
(define MASK_TRUSTLINE_FLAGS_V17 7)
(define MANAGE_DATA 10)
(define MEMO_ID 2)
(define PATH_PAYMENT_STRICT_RECEIVE_SUCCESS 0)
(define LIQUIDITY_POOL_DEPOSIT_NO_TRUST -2)
(define CREATE_CLAIMABLE_BALANCE_MALFORMED -1)
(define MANAGE_SELL_OFFER_SELL_NOT_AUTHORIZED -4)
(define AUTH_REVOCABLE_FLAG 2)
(define PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST -3)
(define ALLOW_TRUST_SELF_NOT_ALLOWED -5)
(define CLAWBACK 19)
(define PASSIVE_FLAG 1)
(define REVOKE_SPONSORSHIP_LOW_RESERVE -3)
(define TRUSTLINE_CLAWBACK_ENABLED_FLAG 4)
(define CHANGE_TRUST_CANNOT_DELETE -7)
(define INFLATION 9)
(define ENVELOPE_TYPE_TX_FEE_BUMP 5)
(define PATH_PAYMENT_STRICT_SEND_SUCCESS 0)
(define MASK_TRUSTLINE_FLAGS_V13 3)
(define PATH_PAYMENT_STRICT_RECEIVE_MALFORMED -1)
(define CLAIMABLE_BALANCE 4)
(define MEMO_TEXT 1)
(define MANAGE_SELL_OFFER_SELL_NO_ISSUER -9)
(define MEMO_NONE 0)
(define ENVELOPE_TYPE_POOL_REVOKE_OP_ID 7)
(define txSUCCESS 0)
(define CLAWBACK_CLAIMABLE_BALANCE 20)
(define KEY_TYPE_ED25519 0)
(define ALLOW_TRUST_NO_TRUST_LINE -2)
(define CREATE_PASSIVE_SELL_OFFER 4)
(define PAYMENT_NO_ISSUER -9)
(define MANAGE_SELL_OFFER_SUCCESS 0)
(define CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM -2)
(define PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF -11)
(define REVOKE_SPONSORSHIP_SIGNER 1)
(define LIQUIDITY_POOL_DEPOSIT_BAD_PRICE -6)
(define PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL -8)
(define MANAGE_BUY_OFFER_LINE_FULL -6)
(define CLAWBACK_SUCCESS 0)
(define ASSET_TYPE_NATIVE 0)
(define opTOO_MANY_SUBENTRIES -4)
(define LIQUIDITY_POOL_WITHDRAW 23)
(define PATH_PAYMENT_STRICT_SEND_UNDERFUNDED -2)
(define txNOT_SUPPORTED -12)
(define TRUE 1)
(define MANAGE_DATA_INVALID_NAME -4)
(define ACCOUNT_MERGE_IS_SPONSOR -7)
(define SET_OPTIONS_TOO_MANY_SIGNERS -2)
(define CLAIM_CLAIMABLE_BALANCE_NO_TRUST -4)
(define PATH_PAYMENT_STRICT_SEND_SRC_NOT_AUTHORIZED -4)
(define txBAD_AUTH -6)
(define MANAGE_DATA_NAME_NOT_FOUND -2)
(define PATH_PAYMENT_STRICT_SEND_NO_ISSUER -9)
(define PAYMENT_SRC_NO_TRUST -3)
(define PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST -3)
(define ACCOUNT_MERGE_IMMUTABLE_SET -3)
(define txINSUFFICIENT_FEE -9)
(define MANAGE_BUY_OFFER_SUCCESS 0)
(define txFEE_BUMP_INNER_FAILED -13)
(define REVOKE_SPONSORSHIP_SUCCESS 0)
(define AUTH_REQUIRED_FLAG 1)
(define PATH_PAYMENT_STRICT_SEND_LINE_FULL -8)
(define MANAGE_SELL_OFFER_BUY_NOT_AUTHORIZED -5)
(define txBAD_SEQ -5)
(define MANAGE_BUY_OFFER_BUY_NO_ISSUER -10)
(define MANAGE_SELL_OFFER_LOW_RESERVE -12)
(define PUBLIC_KEY_TYPE_ED25519 0)
(define CLAIM_PREDICATE_OR 2)
(define CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME 4)
(define SET_TRUST_LINE_FLAGS_INVALID_STATE -4)
(define BEGIN_SPONSORING_FUTURE_RESERVES 16)
(define LIQUIDITY_POOL_DEPOSIT_UNDERFUNDED -4)
(define PATH_PAYMENT_STRICT_SEND_NO_TRUST -6)
(define ACCOUNT_MERGE_SEQNUM_TOO_FAR -5)
(define MANAGE_DATA_NOT_SUPPORTED_YET -1)
(define CHANGE_TRUST_LOW_RESERVE -4)
(define CLAWBACK_UNDERFUNDED -4)
(define SET_TRUST_LINE_FLAGS_MALFORMED -1)
(define PAYMENT_NO_DESTINATION -5)
(define MANAGE_OFFER_UPDATED 1)
(define THRESHOLD_LOW 1)
(define PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN -12)
(define BEGIN_SPONSORING_FUTURE_RESERVES_MALFORMED -1)
(define MASK_TRUSTLINE_FLAGS 1)
(define PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED -7)
(define LIQUIDITY_POOL_DEPOSIT_MALFORMED -1)
(define REVOKE_SPONSORSHIP_DOES_NOT_EXIST -1)
(define opNOT_SUPPORTED -3)
(define PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS -10)
(define AUTH_CLAWBACK_ENABLED_FLAG 8)
(define LIQUIDITY_POOL 5)
(define THRESHOLD_MASTER_WEIGHT 0)
(define PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX -12)
(define CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES -8)
(define txTOO_EARLY -2)
(define SET_TRUST_LINE_FLAGS_CANT_REVOKE -3)
(define MANAGE_SELL_OFFER_UNDERFUNDED -7)
(define MANAGE_BUY_OFFER_SELL_NO_TRUST -2)
(define MANAGE_SELL_OFFER_SELL_NO_TRUST -2)
(define END_SPONSORING_FUTURE_RESERVES_NOT_SPONSORED -1)
(define PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED -7)
(define LIQUIDITY_POOL_WITHDRAW_SUCCESS 0)
(define CLAIM_PREDICATE_BEFORE_RELATIVE_TIME 5)
(define MANAGE_SELL_OFFER_CROSS_SELF -8)
(define LIQUIDITY_POOL_DEPOSIT_NOT_AUTHORIZED -3)
(define LIQUIDITY_POOL_DEPOSIT_LINE_FULL -5)
(define KEY_TYPE_PRE_AUTH_TX 1)
(define THRESHOLD_MED 2)
(define ALLOW_TRUST 7)
(define MANAGE_BUY_OFFER_SELL_NO_ISSUER -9)
(define LIQUIDITY_POOL_WITHDRAW_LINE_FULL -4)
(define txMISSING_OPERATION -4)
(define LIQUIDITY_POOL_WITHDRAW_NO_TRUST -2)
(define LIQUIDITY_POOL_WITHDRAW_UNDERFUNDED -3)
(define CHANGE_TRUST_INVALID_LIMIT -3)
(define CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST -1)
(define CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG 1)
(define CLAWBACK_CLAIMABLE_BALANCE_DOES_NOT_EXIST -1)
(define MANAGE_SELL_OFFER_NOT_FOUND -11)
(define ASSET_TYPE_POOL_SHARE 3)
(define INFLATION_SUCCESS 0)
(define MEMO_RETURN 4)
(define MANAGE_SELL_OFFER 3)
(define KEY_TYPE_HASH_X 2)
(define BEGIN_SPONSORING_FUTURE_RESERVES_SUCCESS 0)
(define PAYMENT_LINE_FULL -8)
(define THRESHOLD_HIGH 3)
(define opNO_ACCOUNT -2)
(define PATH_PAYMENT_STRICT_SEND 13)
(define SET_OPTIONS_BAD_FLAGS -3)
(define ASSET_TYPE_CREDIT_ALPHANUM4 1)
(define BEGIN_SPONSORING_FUTURE_RESERVES_ALREADY_SPONSORED -2)
(define AUTHORIZED_FLAG 1)
(define BUMP_SEQUENCE_SUCCESS 0)
(define txINSUFFICIENT_BALANCE -7)
(define MANAGE_DATA_SUCCESS 0)
(define MAX_OPS_PER_TX 100)
(define MANAGE_BUY_OFFER_BUY_NOT_AUTHORIZED -5)
(define PAYMENT_NO_TRUST -6)
(define txINTERNAL_ERROR -11)
(define BEGIN_SPONSORING_FUTURE_RESERVES_RECURSIVE -3)
(define DATA 3)
(define MANAGE_SELL_OFFER_MALFORMED -1)
(define MANAGE_OFFER_DELETED 2)
(define LIQUIDITY_POOL_WITHDRAW_UNDER_MINIMUM -5)
(define ACCOUNT_MERGE 8)
(define CLAIM_ATOM_TYPE_LIQUIDITY_POOL 2)
(define CREATE_CLAIMABLE_BALANCE_SUCCESS 0)
(define CLAWBACK_CLAIMABLE_BALANCE_SUCCESS 0)
(define SET_OPTIONS_UNKNOWN_FLAG -6)
(define END_SPONSORING_FUTURE_RESERVES_SUCCESS 0)
(define CREATE_CLAIMABLE_BALANCE 14)
(define CLAWBACK_MALFORMED -1)
(define PAYMENT 1)
(define REVOKE_SPONSORSHIP 18)
(define ENVELOPE_TYPE_SCP 1)
(define txTOO_LATE -3)
(define txBAD_AUTH_EXTRA -10)
(define opBAD_AUTH -1)
(define REVOKE_SPONSORSHIP_MALFORMED -5)
(define SET_TRUST_LINE_FLAGS 21)
(define ENVELOPE_TYPE_TX 2)
(define CLAIMABLE_BALANCE_ID_TYPE_V0 0)
(define ALLOW_TRUST_MALFORMED -1)
(define LIQUIDITY_POOL_DEPOSIT 22)
(define LIQUIDITY_POOL_WITHDRAW_MALFORMED -1)
(define ALLOW_TRUST_CANT_REVOKE -4)
(define ACCOUNT_MERGE_HAS_SUB_ENTRIES -4)
(define SIGNER_KEY_TYPE_HASH_X 2)
(define CHANGE_TRUST_SELF_NOT_ALLOWED -5)
(define MANAGE_BUY_OFFER_MALFORMED -1)
(define CLAIM_ATOM_TYPE_V0 0)
(define END_SPONSORING_FUTURE_RESERVES 17)
(define CLAIM_PREDICATE_AND 1)
(define FALSE 0)
(define PAYMENT_MALFORMED -1)
(define SET_TRUST_LINE_FLAGS_NO_TRUST_LINE -2)
(define BUMP_SEQUENCE 11)
(define MANAGE_OFFER_CREATED 0)
(define SIGNER_KEY_TYPE_ED25519 0)
(define SIGNER_KEY_TYPE_PRE_AUTH_TX 1)
(define SET_OPTIONS_AUTH_REVOCABLE_REQUIRED -10)
(define PAYMENT_SUCCESS 0)
(define LIQUIDITY_POOL_DEPOSIT_POOL_FULL -7)
(define txBAD_SPONSORSHIP -14)
(define txFEE_BUMP_INNER_SUCCESS 1)
(define MANAGE_SELL_OFFER_LINE_FULL -6)
(define PATH_PAYMENT_STRICT_SEND_NO_DESTINATION -5)
(define OFFER 2)
(define SET_OPTIONS_THRESHOLD_OUT_OF_RANGE -7)
(define ACCOUNT 0)
(define MANAGE_DATA_LOW_RESERVE -3)
(define PATH_PAYMENT_STRICT_SEND_MALFORMED -1)
(define LIQUIDITY_POOL_FEE_V18 30)
(define CREATE_ACCOUNT_ALREADY_EXIST -4)

; Grammar for TransactionEnvelope: TransactionEnvelope-grammar
(begin
  (struct TransactionV1Envelope (tx signatures) #:transparent)
  (struct LedgerKey::claimableBalance (balanceID) #:transparent)
  (struct CreatePassiveSellOfferOp (selling buying amount price) #:transparent)
  (struct LedgerKey::account (accountID) #:transparent)
  (struct CreateClaimableBalanceOp (asset amount claimants) #:transparent)
  (struct PathPaymentStrictSendOp (sendAsset sendAmount destination destAsset destMin path) #:transparent)
  (struct TimeBounds (minTime maxTime) #:transparent)
  (struct Transaction (sourceAccount fee seqNum timeBounds memo operations ext) #:transparent)
  (struct Signer (key weight) #:transparent)
  (struct BeginSponsoringFutureReservesOp (sponsoredID) #:transparent)
  (struct PaymentOp (destination asset amount) #:transparent)
  (struct LedgerKey::trustLine (accountID asset) #:transparent)
  (struct AllowTrustOp (trustor asset authorize) #:transparent)
  (struct BumpSequenceOp (bumpTo) #:transparent)
  (struct LedgerKey::offer (sellerID offerID) #:transparent)
  (struct Claimant::v0 (destination predicate) #:transparent)
  (struct LedgerKey::liquidityPool (liquidityPoolID) #:transparent)
  (struct SetTrustLineFlagsOp (trustor asset clearFlags setFlags) #:transparent)
  (struct ClawbackClaimableBalanceOp (balanceID) #:transparent)
  (struct LiquidityPoolDepositOp (liquidityPoolID maxAmountA maxAmountB minPrice maxPrice) #:transparent)
  (struct ClawbackOp (asset from amount) #:transparent)
  (struct LiquidityPoolConstantProductParameters (assetA assetB fee) #:transparent)
  (struct LiquidityPoolWithdrawOp (liquidityPoolID amount minAmountA minAmountB) #:transparent)
  (struct ManageDataOp (dataName dataValue) #:transparent)
  (struct PathPaymentStrictReceiveOp (sendAsset sendMax destination destAsset destAmount path) #:transparent)
  (struct TransactionV0Envelope (tx signatures) #:transparent)
  (struct LedgerKey::data (accountID dataName) #:transparent)
  (struct
   SetOptionsOp
   (inflationDest clearFlags setFlags masterWeight lowThreshold medThreshold highThreshold homeDomain signer)
   #:transparent)
  (struct Price (n d) #:transparent)
  (struct FeeBumpTransactionEnvelope (tx signatures) #:transparent)
  (struct FeeBumpTransaction (feeSource fee innerTx ext) #:transparent)
  (struct RevokeSponsorshipOp::signer (accountID signerKey) #:transparent)
  (struct ManageSellOfferOp (selling buying amount price offerID) #:transparent)
  (struct DecoratedSignature (hint signature) #:transparent)
  (struct CreateAccountOp (destination startingBalance) #:transparent)
  (struct ChangeTrustOp (line limit) #:transparent)
  (struct TransactionV0 (sourceAccountEd25519 fee seqNum timeBounds memo operations ext) #:transparent)
  (struct MuxedAccount::med25519 (id ed25519) #:transparent)
  (struct AlphaNum12 (assetCode issuer) #:transparent)
  (struct ManageBuyOfferOp (selling buying buyAmount price offerID) #:transparent)
  (struct ClaimClaimableBalanceOp (balanceID) #:transparent)
  (struct Operation (sourceAccount body) #:transparent)
  (struct AlphaNum4 (assetCode issuer) #:transparent)
  (define-grammar
   (TransactionEnvelope-grammar)
   (TransactionEnvelope-rule
    (choose
     (cons (bv ENVELOPE_TYPE_TX_V0 (bitvector 32)) (TransactionV0Envelope-rule))
     (cons (bv ENVELOPE_TYPE_TX_FEE_BUMP (bitvector 32)) (FeeBumpTransactionEnvelope-rule))
     (cons (bv ENVELOPE_TYPE_TX (bitvector 32)) (TransactionV1Envelope-rule))))
   (FeeBumpTransaction-rule
    (FeeBumpTransaction
     (MuxedAccount-rule)
     (int64-rule)
     (choose (cons (bv ENVELOPE_TYPE_TX (bitvector 32)) (TransactionV1Envelope-rule)))
     (choose (cons (bv 0 (bitvector 32)) null))))
   (Transaction-rule
    (Transaction
     (MuxedAccount-rule)
     (uint32-rule)
     (SequenceNumber-rule)
     (choose (cons (bv TRUE (bitvector 32)) (TimeBounds-rule)) (cons (bv FALSE (bitvector 32)) null))
     (Memo-rule)
     (cons 1 (vector (Operation-rule)))
     (choose (cons (bv 0 (bitvector 32)) null))))
   (TransactionV0-rule
    (TransactionV0
     (uint256-rule)
     (uint32-rule)
     (SequenceNumber-rule)
     (choose (cons (bv TRUE (bitvector 32)) (TimeBounds-rule)) (cons (bv FALSE (bitvector 32)) null))
     (Memo-rule)
     (cons 1 (vector (Operation-rule)))
     (choose (cons (bv 0 (bitvector 32)) null))))
   (DecoratedSignature-rule (DecoratedSignature (SignatureHint-rule) (Signature-rule)))
   (Signature-rule (cons 64 (?? (bitvector 512))))
   (SignatureHint-rule (?? (bitvector 32)))
   (TimePoint-rule (uint64-rule))
   (MemoType-rule
    (choose (bv 3 (bitvector 32)) (bv 2 (bitvector 32)) (bv 1 (bitvector 32)) (bv 0 (bitvector 32)) (bv 4 (bitvector 32))))
   (MuxedAccount-rule
    (choose
     (cons (bv KEY_TYPE_MUXED_ED25519 (bitvector 32)) (MuxedAccount::med25519 (uint64-rule) (uint256-rule)))
     (cons (bv KEY_TYPE_ED25519 (bitvector 32)) (uint256-rule))))
   (SetOptionsOp-rule
    (SetOptionsOp
     (choose (cons (bv TRUE (bitvector 32)) (AccountID-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (uint32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (uint32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (uint32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (uint32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (uint32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (uint32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (string32-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose (cons (bv TRUE (bitvector 32)) (Signer-rule)) (cons (bv FALSE (bitvector 32)) null))))
   (CreateAccountOp-rule (CreateAccountOp (AccountID-rule) (int64-rule)))
   (PathPaymentStrictReceiveOp-rule
    (PathPaymentStrictReceiveOp (Asset-rule) (int64-rule) (MuxedAccount-rule) (Asset-rule) (int64-rule) (cons 1 (vector (Asset-rule)))))
   (ManageDataOp-rule
    (ManageDataOp (string64-rule) (choose (cons (bv TRUE (bitvector 32)) (DataValue-rule)) (cons (bv FALSE (bitvector 32)) null))))
   (ChangeTrustOp-rule (ChangeTrustOp (ChangeTrustAsset-rule) (int64-rule)))
   (ClawbackOp-rule (ClawbackOp (Asset-rule) (MuxedAccount-rule) (int64-rule)))
   (ClawbackClaimableBalanceOp-rule (ClawbackClaimableBalanceOp (ClaimableBalanceID-rule)))
   (CreatePassiveSellOfferOp-rule (CreatePassiveSellOfferOp (Asset-rule) (Asset-rule) (int64-rule) (Price-rule)))
   (ManageSellOfferOp-rule (ManageSellOfferOp (Asset-rule) (Asset-rule) (int64-rule) (Price-rule) (int64-rule)))
   (PathPaymentStrictSendOp-rule
    (PathPaymentStrictSendOp (Asset-rule) (int64-rule) (MuxedAccount-rule) (Asset-rule) (int64-rule) (cons 1 (vector (Asset-rule)))))
   (CreateClaimableBalanceOp-rule (CreateClaimableBalanceOp (Asset-rule) (int64-rule) (cons 1 (vector (Claimant-rule)))))
   (PaymentOp-rule (PaymentOp (MuxedAccount-rule) (Asset-rule) (int64-rule)))
   (LiquidityPoolDepositOp-rule (LiquidityPoolDepositOp (PoolID-rule) (int64-rule) (int64-rule) (Price-rule) (Price-rule)))
   (RevokeSponsorshipOp-rule
    (choose
     (cons (bv REVOKE_SPONSORSHIP_LEDGER_ENTRY (bitvector 32)) (LedgerKey-rule))
     (cons (bv REVOKE_SPONSORSHIP_SIGNER (bitvector 32)) (RevokeSponsorshipOp::signer (AccountID-rule) (SignerKey-rule)))))
   (SetTrustLineFlagsOp-rule (SetTrustLineFlagsOp (AccountID-rule) (Asset-rule) (uint32-rule) (uint32-rule)))
   (BumpSequenceOp-rule (BumpSequenceOp (SequenceNumber-rule)))
   (ClaimClaimableBalanceOp-rule (ClaimClaimableBalanceOp (ClaimableBalanceID-rule)))
   (ManageBuyOfferOp-rule (ManageBuyOfferOp (Asset-rule) (Asset-rule) (int64-rule) (Price-rule) (int64-rule)))
   (LiquidityPoolWithdrawOp-rule (LiquidityPoolWithdrawOp (PoolID-rule) (int64-rule) (int64-rule) (int64-rule)))
   (BeginSponsoringFutureReservesOp-rule (BeginSponsoringFutureReservesOp (AccountID-rule)))
   (AllowTrustOp-rule (AllowTrustOp (AccountID-rule) (AssetCode-rule) (uint32-rule)))
   (OperationType-rule
    (choose
     (bv 5 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv 2 (bitvector 32))
     (bv 10 (bitvector 32))
     (bv 6 (bitvector 32))
     (bv 9 (bitvector 32))
     (bv 19 (bitvector 32))
     (bv 20 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 3 (bitvector 32))
     (bv 13 (bitvector 32))
     (bv 14 (bitvector 32))
     (bv 1 (bitvector 32))
     (bv 22 (bitvector 32))
     (bv 18 (bitvector 32))
     (bv 21 (bitvector 32))
     (bv 11 (bitvector 32))
     (bv 17 (bitvector 32))
     (bv 15 (bitvector 32))
     (bv 12 (bitvector 32))
     (bv 23 (bitvector 32))
     (bv 16 (bitvector 32))
     (bv 7 (bitvector 32))
     (bv 8 (bitvector 32))))
   (PublicKey-rule (choose (cons (bv PUBLIC_KEY_TYPE_ED25519 (bitvector 32)) (uint256-rule))))
   (PublicKeyType-rule (choose (bv 0 (bitvector 32))))
   (AssetType-rule (choose (bv 3 (bitvector 32)) (bv 1 (bitvector 32)) (bv 2 (bitvector 32)) (bv 0 (bitvector 32))))
   (AssetCode4-rule (?? (bitvector 32)))
   (AssetCode12-rule (?? (bitvector 96)))
   (AssetCode-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AssetCode12-rule))
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AssetCode4-rule))))
   (AccountID-rule (PublicKey-rule))
   (Hash-rule (?? (bitvector 256)))
   (int64-rule (?? (bitvector 64)))
   (PoolID-rule (Hash-rule))
   (AlphaNum4-rule (AlphaNum4 (AssetCode4-rule) (AccountID-rule)))
   (AlphaNum12-rule (AlphaNum12 (AssetCode12-rule) (AccountID-rule)))
   (int32-rule (?? (bitvector 32)))
   (Price-rule (Price (int32-rule) (int32-rule)))
   (Asset-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AlphaNum12-rule))
     (cons (bv ASSET_TYPE_NATIVE (bitvector 32)) null)
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AlphaNum4-rule))))
   (ClaimableBalanceIDType-rule (choose (bv 0 (bitvector 32))))
   (ClaimableBalanceID-rule (choose (cons (bv CLAIMABLE_BALANCE_ID_TYPE_V0 (bitvector 32)) (Hash-rule))))
   (SignerKeyType-rule (choose (bv 0 (bitvector 32)) (bv 1 (bitvector 32)) (bv 2 (bitvector 32))))
   (LedgerEntryType-rule
    (choose
     (bv 2 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv 1 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 5 (bitvector 32))
     (bv 3 (bitvector 32))))
   (string64-rule (cons (bv 2 32) (?? (bitvector 64))))
   (TrustLineAsset-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AlphaNum12-rule))
     (cons (bv ASSET_TYPE_NATIVE (bitvector 32)) null)
     (cons (bv ASSET_TYPE_POOL_SHARE (bitvector 32)) (PoolID-rule))
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AlphaNum4-rule))))
   (LedgerKey-rule
    (choose
     (cons (bv TRUSTLINE (bitvector 32)) (LedgerKey::trustLine (AccountID-rule) (TrustLineAsset-rule)))
     (cons (bv CLAIMABLE_BALANCE (bitvector 32)) (LedgerKey::claimableBalance (ClaimableBalanceID-rule)))
     (cons (bv LIQUIDITY_POOL (bitvector 32)) (LedgerKey::liquidityPool (PoolID-rule)))
     (cons (bv DATA (bitvector 32)) (LedgerKey::data (AccountID-rule) (string64-rule)))
     (cons (bv OFFER (bitvector 32)) (LedgerKey::offer (AccountID-rule) (int64-rule)))
     (cons (bv ACCOUNT (bitvector 32)) (LedgerKey::account (AccountID-rule)))))
   (SignerKey-rule
    (choose
     (cons (bv SIGNER_KEY_TYPE_HASH_X (bitvector 32)) (uint256-rule))
     (cons (bv SIGNER_KEY_TYPE_ED25519 (bitvector 32)) (uint256-rule))
     (cons (bv SIGNER_KEY_TYPE_PRE_AUTH_TX (bitvector 32)) (uint256-rule))))
   (RevokeSponsorshipType-rule (choose (bv 0 (bitvector 32)) (bv 1 (bitvector 32))))
   (CryptoKeyType-rule (choose (bv 256 (bitvector 32)) (bv 0 (bitvector 32)) (bv 1 (bitvector 32)) (bv 2 (bitvector 32))))
   (uint64-rule (?? (bitvector 64)))
   (ClaimantType-rule (choose (bv 0 (bitvector 32))))
   (ClaimPredicate-rule
    (choose
     (cons (bv CLAIM_PREDICATE_UNCONDITIONAL (bitvector 32)) null)
     (cons
      (bv CLAIM_PREDICATE_NOT (bitvector 32))
      (choose (cons (bv TRUE (bitvector 32)) (ClaimPredicate-rule)) (cons (bv FALSE (bitvector 32)) null)))
     (cons (bv CLAIM_PREDICATE_BEFORE_RELATIVE_TIME (bitvector 32)) (int64-rule))
     (cons (bv CLAIM_PREDICATE_AND (bitvector 32)) (cons 1 (vector (ClaimPredicate-rule))))
     (cons (bv CLAIM_PREDICATE_OR (bitvector 32)) (cons 1 (vector (ClaimPredicate-rule))))
     (cons (bv CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME (bitvector 32)) (int64-rule))))
   (ClaimPredicateType-rule
    (choose
     (bv 2 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv 3 (bitvector 32))
     (bv 5 (bitvector 32))
     (bv 1 (bitvector 32))))
   (Claimant-rule (choose (cons (bv CLAIMANT_TYPE_V0 (bitvector 32)) (Claimant::v0 (AccountID-rule) (ClaimPredicate-rule)))))
   (LiquidityPoolParameters-rule
    (choose (cons (bv LIQUIDITY_POOL_CONSTANT_PRODUCT (bitvector 32)) (LiquidityPoolConstantProductParameters-rule))))
   (LiquidityPoolConstantProductParameters-rule (LiquidityPoolConstantProductParameters (Asset-rule) (Asset-rule) (int32-rule)))
   (LiquidityPoolType-rule (choose (bv 0 (bitvector 32))))
   (ChangeTrustAsset-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AlphaNum12-rule))
     (cons (bv ASSET_TYPE_NATIVE (bitvector 32)) null)
     (cons (bv ASSET_TYPE_POOL_SHARE (bitvector 32)) (LiquidityPoolParameters-rule))
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AlphaNum4-rule))))
   (DataValue-rule (cons 64 (?? (bitvector 512))))
   (Signer-rule (Signer (SignerKey-rule) (uint32-rule)))
   (string32-rule (cons (bv 2 32) (?? (bitvector 64))))
   (Operation-rule
    (Operation
     (choose (cons (bv TRUE (bitvector 32)) (MuxedAccount-rule)) (cons (bv FALSE (bitvector 32)) null))
     (choose
      (cons (bv CLAIM_CLAIMABLE_BALANCE (bitvector 32)) (ClaimClaimableBalanceOp-rule))
      (cons (bv MANAGE_BUY_OFFER (bitvector 32)) (ManageBuyOfferOp-rule))
      (cons (bv LIQUIDITY_POOL_WITHDRAW (bitvector 32)) (LiquidityPoolWithdrawOp-rule))
      (cons (bv BEGIN_SPONSORING_FUTURE_RESERVES (bitvector 32)) (BeginSponsoringFutureReservesOp-rule))
      (cons (bv ALLOW_TRUST (bitvector 32)) (AllowTrustOp-rule))
      (cons (bv ACCOUNT_MERGE (bitvector 32)) (MuxedAccount-rule))
      (cons (bv SET_OPTIONS (bitvector 32)) (SetOptionsOp-rule))
      (cons (bv CREATE_ACCOUNT (bitvector 32)) (CreateAccountOp-rule))
      (cons (bv PATH_PAYMENT_STRICT_RECEIVE (bitvector 32)) (PathPaymentStrictReceiveOp-rule))
      (cons (bv MANAGE_DATA (bitvector 32)) (ManageDataOp-rule))
      (cons (bv CHANGE_TRUST (bitvector 32)) (ChangeTrustOp-rule))
      (cons (bv INFLATION (bitvector 32)) null)
      (cons (bv CLAWBACK (bitvector 32)) (ClawbackOp-rule))
      (cons (bv CLAWBACK_CLAIMABLE_BALANCE (bitvector 32)) (ClawbackClaimableBalanceOp-rule))
      (cons (bv CREATE_PASSIVE_SELL_OFFER (bitvector 32)) (CreatePassiveSellOfferOp-rule))
      (cons (bv MANAGE_SELL_OFFER (bitvector 32)) (ManageSellOfferOp-rule))
      (cons (bv PATH_PAYMENT_STRICT_SEND (bitvector 32)) (PathPaymentStrictSendOp-rule))
      (cons (bv LIQUIDITY_POOL_DEPOSIT (bitvector 32)) (LiquidityPoolDepositOp-rule))
      (cons (bv REVOKE_SPONSORSHIP (bitvector 32)) (RevokeSponsorshipOp-rule))
      (cons (bv SET_TRUST_LINE_FLAGS (bitvector 32)) (SetTrustLineFlagsOp-rule))
      (cons (bv CREATE_CLAIMABLE_BALANCE (bitvector 32)) (CreateClaimableBalanceOp-rule))
      (cons (bv PAYMENT (bitvector 32)) (PaymentOp-rule))
      (cons (bv BUMP_SEQUENCE (bitvector 32)) (BumpSequenceOp-rule))
      (cons (bv END_SPONSORING_FUTURE_RESERVES (bitvector 32)) null))))
   (Memo-rule
    (choose
     (cons (bv MEMO_RETURN (bitvector 32)) (Hash-rule))
     (cons (bv MEMO_HASH (bitvector 32)) (Hash-rule))
     (cons (bv MEMO_ID (bitvector 32)) (uint64-rule))
     (cons (bv MEMO_TEXT (bitvector 32)) (cons (bv 2 32) (?? (bitvector 64))))
     (cons (bv MEMO_NONE (bitvector 32)) null)))
   (bool-rule (choose (bv 1 (bitvector 32)) (bv 0 (bitvector 32))))
   (TimeBounds-rule (TimeBounds (TimePoint-rule) (TimePoint-rule)))
   (SequenceNumber-rule (int64-rule))
   (uint32-rule (?? (bitvector 32)))
   (uint256-rule (?? (bitvector 256)))
   (TransactionV0Envelope-rule (TransactionV0Envelope (TransactionV0-rule) (cons 1 (vector (DecoratedSignature-rule)))))
   (FeeBumpTransactionEnvelope-rule (FeeBumpTransactionEnvelope (FeeBumpTransaction-rule) (cons 1 (vector (DecoratedSignature-rule)))))
   (TransactionV1Envelope-rule (TransactionV1Envelope (Transaction-rule) (cons 1 (vector (DecoratedSignature-rule)))))
   (EnvelopeType-rule
    (choose
     (bv 0 (bitvector 32))
     (bv 3 (bitvector 32))
     (bv 1 (bitvector 32))
     (bv 2 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 6 (bitvector 32))
     (bv 5 (bitvector 32))
     (bv 7 (bitvector 32))))))

; grammar for TransactionResult
(begin
  (struct ClaimOfferAtom (sellerID offerID assetSold amountSold assetBought amountBought) #:transparent)
  (struct TransactionResult (feeCharged result ext) #:transparent)
  (struct ClaimOfferAtomV0 (sellerEd25519 offerID assetSold amountSold assetBought amountBought) #:transparent)
  (struct PathPaymentStrictReceiveResult::success (offers last) #:transparent)
  (struct ClaimLiquidityAtom (liquidityPoolID assetSold amountSold assetBought amountBought) #:transparent)
  (struct OfferEntry (sellerID offerID selling buying amount price flags ext) #:transparent)
  (struct InnerTransactionResultPair (transactionHash result) #:transparent)
  (struct ManageOfferSuccessResult (offersClaimed offer) #:transparent)
  (struct PathPaymentStrictSendResult::success (offers last) #:transparent)
  (struct SimplePaymentResult (destination asset amount) #:transparent)
  (struct InflationPayout (destination amount) #:transparent)
  (struct InnerTransactionResult (feeCharged result ext) #:transparent)
  (define-grammar
   (TransactionResult-grammar)
   (TransactionResult-rule
    (TransactionResult
     (int64-rule)
     (choose
      (cons (bv txFAILED (bitvector 32)) (cons 1 (vector (OperationResult-rule))))
      (cons (bv txNO_ACCOUNT (bitvector 32)) null)
      (cons (bv txSUCCESS (bitvector 32)) (cons 1 (vector (OperationResult-rule))))
      (cons (bv txBAD_SEQ (bitvector 32)) null)
      (cons (bv txINSUFFICIENT_FEE (bitvector 32)) null)
      (cons (bv txNOT_SUPPORTED (bitvector 32)) null)
      (cons (bv txFEE_BUMP_INNER_FAILED (bitvector 32)) (InnerTransactionResultPair-rule))
      (cons (bv txBAD_AUTH (bitvector 32)) null)
      (cons (bv txTOO_EARLY (bitvector 32)) null)
      (cons (bv txMISSING_OPERATION (bitvector 32)) null)
      (cons (bv txINSUFFICIENT_BALANCE (bitvector 32)) null)
      (cons (bv txINTERNAL_ERROR (bitvector 32)) null)
      (cons (bv txTOO_LATE (bitvector 32)) null)
      (cons (bv txBAD_AUTH_EXTRA (bitvector 32)) null)
      (cons (bv txBAD_SPONSORSHIP (bitvector 32)) null)
      (cons (bv txFEE_BUMP_INNER_SUCCESS (bitvector 32)) (InnerTransactionResultPair-rule)))
     (choose (cons (bv 0 (bitvector 32)) null))))
   (Hash-rule (?? (bitvector 256)))
   (InnerTransactionResult-rule
    (InnerTransactionResult
     (int64-rule)
     (choose
      (cons (bv txFAILED (bitvector 32)) (cons 1 (vector (OperationResult-rule))))
      (cons (bv txNO_ACCOUNT (bitvector 32)) null)
      (cons (bv txSUCCESS (bitvector 32)) (cons 1 (vector (OperationResult-rule))))
      (cons (bv txBAD_SEQ (bitvector 32)) null)
      (cons (bv txBAD_SPONSORSHIP (bitvector 32)) null)
      (cons (bv txINSUFFICIENT_FEE (bitvector 32)) null)
      (cons (bv txNOT_SUPPORTED (bitvector 32)) null)
      (cons (bv txBAD_AUTH (bitvector 32)) null)
      (cons (bv txTOO_EARLY (bitvector 32)) null)
      (cons (bv txMISSING_OPERATION (bitvector 32)) null)
      (cons (bv txINSUFFICIENT_BALANCE (bitvector 32)) null)
      (cons (bv txINTERNAL_ERROR (bitvector 32)) null)
      (cons (bv txTOO_LATE (bitvector 32)) null)
      (cons (bv txBAD_AUTH_EXTRA (bitvector 32)) null))
     (choose (cons (bv 0 (bitvector 32)) null))))
   (OperationResultCode-rule
    (choose
     (bv -6 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -1 (bitvector 32))))
   (SetOptionsResult-rule
    (choose
     (cons (bv SET_OPTIONS_SUCCESS (bitvector 32)) null)
     (cons (bv SET_OPTIONS_LOW_RESERVE (bitvector 32)) null)
     (cons (bv SET_OPTIONS_TOO_MANY_SIGNERS (bitvector 32)) null)
     (cons (bv SET_OPTIONS_BAD_FLAGS (bitvector 32)) null)
     (cons (bv SET_OPTIONS_UNKNOWN_FLAG (bitvector 32)) null)
     (cons (bv SET_OPTIONS_BAD_SIGNER (bitvector 32)) null)
     (cons (bv SET_OPTIONS_INVALID_INFLATION (bitvector 32)) null)
     (cons (bv SET_OPTIONS_CANT_CHANGE (bitvector 32)) null)
     (cons (bv SET_OPTIONS_INVALID_HOME_DOMAIN (bitvector 32)) null)
     (cons (bv SET_OPTIONS_AUTH_REVOCABLE_REQUIRED (bitvector 32)) null)
     (cons (bv SET_OPTIONS_THRESHOLD_OUT_OF_RANGE (bitvector 32)) null)))
   (CreateAccountResult-rule
    (choose
     (cons (bv CREATE_ACCOUNT_SUCCESS (bitvector 32)) null)
     (cons (bv CREATE_ACCOUNT_UNDERFUNDED (bitvector 32)) null)
     (cons (bv CREATE_ACCOUNT_ALREADY_EXIST (bitvector 32)) null)
     (cons (bv CREATE_ACCOUNT_LOW_RESERVE (bitvector 32)) null)
     (cons (bv CREATE_ACCOUNT_MALFORMED (bitvector 32)) null)))
   (PathPaymentStrictReceiveResult-rule
    (choose
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_MALFORMED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER (bitvector 32)) (Asset-rule))
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_SRC_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST (bitvector 32)) null)
     (cons
      (bv PATH_PAYMENT_STRICT_RECEIVE_SUCCESS (bitvector 32))
      (PathPaymentStrictReceiveResult::success (cons 1 (vector (ClaimAtom-rule))) (SimplePaymentResult-rule)))
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL (bitvector 32)) null)))
   (ManageDataResult-rule
    (choose
     (cons (bv MANAGE_DATA_NOT_SUPPORTED_YET (bitvector 32)) null)
     (cons (bv MANAGE_DATA_SUCCESS (bitvector 32)) null)
     (cons (bv MANAGE_DATA_LOW_RESERVE (bitvector 32)) null)
     (cons (bv MANAGE_DATA_INVALID_NAME (bitvector 32)) null)
     (cons (bv MANAGE_DATA_NAME_NOT_FOUND (bitvector 32)) null)))
   (ChangeTrustResult-rule
    (choose
     (cons (bv CHANGE_TRUST_TRUST_LINE_MISSING (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_CANNOT_DELETE (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_LOW_RESERVE (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_INVALID_LIMIT (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_SELF_NOT_ALLOWED (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_MALFORMED (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_NO_ISSUER (bitvector 32)) null)
     (cons (bv CHANGE_TRUST_SUCCESS (bitvector 32)) null)))
   (InflationResult-rule
    (choose
     (cons (bv INFLATION_NOT_TIME (bitvector 32)) null)
     (cons (bv INFLATION_SUCCESS (bitvector 32)) (cons 1 (vector (InflationPayout-rule))))))
   (ClawbackResult-rule
    (choose
     (cons (bv CLAWBACK_SUCCESS (bitvector 32)) null)
     (cons (bv CLAWBACK_UNDERFUNDED (bitvector 32)) null)
     (cons (bv CLAWBACK_MALFORMED (bitvector 32)) null)
     (cons (bv CLAWBACK_NO_TRUST (bitvector 32)) null)
     (cons (bv CLAWBACK_NOT_CLAWBACK_ENABLED (bitvector 32)) null)))
   (ClawbackClaimableBalanceResult-rule
    (choose
     (cons (bv CLAWBACK_CLAIMABLE_BALANCE_NOT_CLAWBACK_ENABLED (bitvector 32)) null)
     (cons (bv CLAWBACK_CLAIMABLE_BALANCE_NOT_ISSUER (bitvector 32)) null)
     (cons (bv CLAWBACK_CLAIMABLE_BALANCE_DOES_NOT_EXIST (bitvector 32)) null)
     (cons (bv CLAWBACK_CLAIMABLE_BALANCE_SUCCESS (bitvector 32)) null)))
   (ManageSellOfferResult-rule
    (choose
     (cons (bv MANAGE_SELL_OFFER_BUY_NO_TRUST (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_BUY_NO_ISSUER (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_SELL_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_NOT_FOUND (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_MALFORMED (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_LINE_FULL (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_SELL_NO_ISSUER (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_SUCCESS (bitvector 32)) (ManageOfferSuccessResult-rule))
     (cons (bv MANAGE_SELL_OFFER_BUY_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_LOW_RESERVE (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_UNDERFUNDED (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_SELL_NO_TRUST (bitvector 32)) null)
     (cons (bv MANAGE_SELL_OFFER_CROSS_SELF (bitvector 32)) null)))
   (PathPaymentStrictSendResult-rule
    (choose
     (cons (bv PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF (bitvector 32)) null)
     (cons
      (bv PATH_PAYMENT_STRICT_SEND_SUCCESS (bitvector 32))
      (PathPaymentStrictSendResult::success (cons 1 (vector (ClaimAtom-rule))) (SimplePaymentResult-rule)))
     (cons (bv PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_UNDERFUNDED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_SRC_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_NO_ISSUER (bitvector 32)) (Asset-rule))
     (cons (bv PATH_PAYMENT_STRICT_SEND_NO_TRUST (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_LINE_FULL (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_MALFORMED (bitvector 32)) null)
     (cons (bv PATH_PAYMENT_STRICT_SEND_NO_DESTINATION (bitvector 32)) null)))
   (CreateClaimableBalanceResult-rule
    (choose
     (cons (bv CREATE_CLAIMABLE_BALANCE_LOW_RESERVE (bitvector 32)) null)
     (cons (bv CREATE_CLAIMABLE_BALANCE_UNDERFUNDED (bitvector 32)) null)
     (cons (bv CREATE_CLAIMABLE_BALANCE_MALFORMED (bitvector 32)) null)
     (cons (bv CREATE_CLAIMABLE_BALANCE_SUCCESS (bitvector 32)) (ClaimableBalanceID-rule))
     (cons (bv CREATE_CLAIMABLE_BALANCE_NO_TRUST (bitvector 32)) null)
     (cons (bv CREATE_CLAIMABLE_BALANCE_NOT_AUTHORIZED (bitvector 32)) null)))
   (PaymentResult-rule
    (choose
     (cons (bv PAYMENT_SRC_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv PAYMENT_UNDERFUNDED (bitvector 32)) null)
     (cons (bv PAYMENT_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv PAYMENT_NO_ISSUER (bitvector 32)) null)
     (cons (bv PAYMENT_SRC_NO_TRUST (bitvector 32)) null)
     (cons (bv PAYMENT_NO_DESTINATION (bitvector 32)) null)
     (cons (bv PAYMENT_LINE_FULL (bitvector 32)) null)
     (cons (bv PAYMENT_NO_TRUST (bitvector 32)) null)
     (cons (bv PAYMENT_MALFORMED (bitvector 32)) null)
     (cons (bv PAYMENT_SUCCESS (bitvector 32)) null)))
   (LiquidityPoolDepositResult-rule
    (choose
     (cons (bv LIQUIDITY_POOL_DEPOSIT_SUCCESS (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_NO_TRUST (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_BAD_PRICE (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_UNDERFUNDED (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_MALFORMED (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_POOL_FULL (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_DEPOSIT_LINE_FULL (bitvector 32)) null)))
   (RevokeSponsorshipResult-rule
    (choose
     (cons (bv REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE (bitvector 32)) null)
     (cons (bv REVOKE_SPONSORSHIP_NOT_SPONSOR (bitvector 32)) null)
     (cons (bv REVOKE_SPONSORSHIP_LOW_RESERVE (bitvector 32)) null)
     (cons (bv REVOKE_SPONSORSHIP_SUCCESS (bitvector 32)) null)
     (cons (bv REVOKE_SPONSORSHIP_DOES_NOT_EXIST (bitvector 32)) null)
     (cons (bv REVOKE_SPONSORSHIP_MALFORMED (bitvector 32)) null)))
   (SetTrustLineFlagsResult-rule
    (choose
     (cons (bv SET_TRUST_LINE_FLAGS_SUCCESS (bitvector 32)) null)
     (cons (bv SET_TRUST_LINE_FLAGS_LOW_RESERVE (bitvector 32)) null)
     (cons (bv SET_TRUST_LINE_FLAGS_CANT_REVOKE (bitvector 32)) null)
     (cons (bv SET_TRUST_LINE_FLAGS_NO_TRUST_LINE (bitvector 32)) null)
     (cons (bv SET_TRUST_LINE_FLAGS_INVALID_STATE (bitvector 32)) null)
     (cons (bv SET_TRUST_LINE_FLAGS_MALFORMED (bitvector 32)) null)))
   (BumpSequenceResult-rule
    (choose (cons (bv BUMP_SEQUENCE_BAD_SEQ (bitvector 32)) null) (cons (bv BUMP_SEQUENCE_SUCCESS (bitvector 32)) null)))
   (EndSponsoringFutureReservesResult-rule
    (choose
     (cons (bv END_SPONSORING_FUTURE_RESERVES_NOT_SPONSORED (bitvector 32)) null)
     (cons (bv END_SPONSORING_FUTURE_RESERVES_SUCCESS (bitvector 32)) null)))
   (ClaimClaimableBalanceResult-rule
    (choose
     (cons (bv CLAIM_CLAIMABLE_BALANCE_LINE_FULL (bitvector 32)) null)
     (cons (bv CLAIM_CLAIMABLE_BALANCE_SUCCESS (bitvector 32)) null)
     (cons (bv CLAIM_CLAIMABLE_BALANCE_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM (bitvector 32)) null)
     (cons (bv CLAIM_CLAIMABLE_BALANCE_NO_TRUST (bitvector 32)) null)
     (cons (bv CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST (bitvector 32)) null)))
   (ManageBuyOfferResult-rule
    (choose
     (cons (bv MANAGE_BUY_OFFER_BUY_NO_ISSUER (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_BUY_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_MALFORMED (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_LOW_RESERVE (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_UNDERFUNDED (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_CROSS_SELF (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_SELL_NOT_AUTHORIZED (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_NOT_FOUND (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_BUY_NO_TRUST (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_LINE_FULL (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_SUCCESS (bitvector 32)) (ManageOfferSuccessResult-rule))
     (cons (bv MANAGE_BUY_OFFER_SELL_NO_TRUST (bitvector 32)) null)
     (cons (bv MANAGE_BUY_OFFER_SELL_NO_ISSUER (bitvector 32)) null)))
   (LiquidityPoolWithdrawResult-rule
    (choose
     (cons (bv LIQUIDITY_POOL_WITHDRAW_UNDER_MINIMUM (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_WITHDRAW_MALFORMED (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_WITHDRAW_LINE_FULL (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_WITHDRAW_SUCCESS (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_WITHDRAW_NO_TRUST (bitvector 32)) null)
     (cons (bv LIQUIDITY_POOL_WITHDRAW_UNDERFUNDED (bitvector 32)) null)))
   (BeginSponsoringFutureReservesResult-rule
    (choose
     (cons (bv BEGIN_SPONSORING_FUTURE_RESERVES_MALFORMED (bitvector 32)) null)
     (cons (bv BEGIN_SPONSORING_FUTURE_RESERVES_SUCCESS (bitvector 32)) null)
     (cons (bv BEGIN_SPONSORING_FUTURE_RESERVES_ALREADY_SPONSORED (bitvector 32)) null)
     (cons (bv BEGIN_SPONSORING_FUTURE_RESERVES_RECURSIVE (bitvector 32)) null)))
   (AllowTrustResult-rule
    (choose
     (cons (bv ALLOW_TRUST_LOW_RESERVE (bitvector 32)) null)
     (cons (bv ALLOW_TRUST_TRUST_NOT_REQUIRED (bitvector 32)) null)
     (cons (bv ALLOW_TRUST_SUCCESS (bitvector 32)) null)
     (cons (bv ALLOW_TRUST_SELF_NOT_ALLOWED (bitvector 32)) null)
     (cons (bv ALLOW_TRUST_NO_TRUST_LINE (bitvector 32)) null)
     (cons (bv ALLOW_TRUST_CANT_REVOKE (bitvector 32)) null)
     (cons (bv ALLOW_TRUST_MALFORMED (bitvector 32)) null)))
   (AccountMergeResult-rule
    (choose
     (cons (bv ACCOUNT_MERGE_NO_ACCOUNT (bitvector 32)) null)
     (cons (bv ACCOUNT_MERGE_MALFORMED (bitvector 32)) null)
     (cons (bv ACCOUNT_MERGE_SEQNUM_TOO_FAR (bitvector 32)) null)
     (cons (bv ACCOUNT_MERGE_HAS_SUB_ENTRIES (bitvector 32)) null)
     (cons (bv ACCOUNT_MERGE_SUCCESS (bitvector 32)) (int64-rule))
     (cons (bv ACCOUNT_MERGE_DEST_FULL (bitvector 32)) null)
     (cons (bv ACCOUNT_MERGE_IMMUTABLE_SET (bitvector 32)) null)
     (cons (bv ACCOUNT_MERGE_IS_SPONSOR (bitvector 32)) null)))
   (OperationType-rule
    (choose
     (bv 5 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv 2 (bitvector 32))
     (bv 10 (bitvector 32))
     (bv 6 (bitvector 32))
     (bv 9 (bitvector 32))
     (bv 19 (bitvector 32))
     (bv 20 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 3 (bitvector 32))
     (bv 13 (bitvector 32))
     (bv 14 (bitvector 32))
     (bv 1 (bitvector 32))
     (bv 22 (bitvector 32))
     (bv 18 (bitvector 32))
     (bv 21 (bitvector 32))
     (bv 11 (bitvector 32))
     (bv 17 (bitvector 32))
     (bv 15 (bitvector 32))
     (bv 12 (bitvector 32))
     (bv 23 (bitvector 32))
     (bv 16 (bitvector 32))
     (bv 7 (bitvector 32))
     (bv 8 (bitvector 32))))
   (AccountMergeResultCode-rule
    (choose
     (bv 0 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -4 (bitvector 32))))
   (AllowTrustResultCode-rule
    (choose
     (bv -4 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -2 (bitvector 32))))
   (BeginSponsoringFutureReservesResultCode-rule
    (choose (bv -2 (bitvector 32)) (bv -3 (bitvector 32)) (bv -1 (bitvector 32)) (bv 0 (bitvector 32))))
   (LiquidityPoolWithdrawResultCode-rule
    (choose
     (bv -4 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -1 (bitvector 32))))
   (ClaimAtom-rule
    (choose
     (cons (bv CLAIM_ATOM_TYPE_ORDER_BOOK (bitvector 32)) (ClaimOfferAtom-rule))
     (cons (bv CLAIM_ATOM_TYPE_LIQUIDITY_POOL (bitvector 32)) (ClaimLiquidityAtom-rule))
     (cons (bv CLAIM_ATOM_TYPE_V0 (bitvector 32)) (ClaimOfferAtomV0-rule))))
   (OfferEntry-rule
    (OfferEntry
     (AccountID-rule)
     (int64-rule)
     (Asset-rule)
     (Asset-rule)
     (int64-rule)
     (Price-rule)
     (uint32-rule)
     (choose (cons (bv 0 (bitvector 32)) null))))
   (ManageOfferEffect-rule (choose (bv 1 (bitvector 32)) (bv 2 (bitvector 32)) (bv 0 (bitvector 32))))
   (AssetType-rule (choose (bv 3 (bitvector 32)) (bv 1 (bitvector 32)) (bv 2 (bitvector 32)) (bv 0 (bitvector 32))))
   (AlphaNum4-rule (AlphaNum4 (AssetCode4-rule) (AccountID-rule)))
   (AlphaNum12-rule (AlphaNum12 (AssetCode12-rule) (AccountID-rule)))
   (PublicKey-rule (choose (cons (bv PUBLIC_KEY_TYPE_ED25519 (bitvector 32)) (uint256-rule))))
   (uint256-rule (?? (bitvector 256)))
   (PublicKeyType-rule (choose (bv 0 (bitvector 32))))
   (AssetCode12-rule (?? (bitvector 96)))
   (AssetCode4-rule (?? (bitvector 32)))
   (int32-rule (?? (bitvector 32)))
   (uint32-rule (?? (bitvector 32)))
   (Price-rule (Price (int32-rule) (int32-rule)))
   (Asset-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AlphaNum12-rule))
     (cons (bv ASSET_TYPE_NATIVE (bitvector 32)) null)
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AlphaNum4-rule))))
   (AccountID-rule (PublicKey-rule))
   (PoolID-rule (Hash-rule))
   (ClaimOfferAtom-rule (ClaimOfferAtom (AccountID-rule) (int64-rule) (Asset-rule) (int64-rule) (Asset-rule) (int64-rule)))
   (ClaimLiquidityAtom-rule (ClaimLiquidityAtom (PoolID-rule) (Asset-rule) (int64-rule) (Asset-rule) (int64-rule)))
   (ClaimOfferAtomV0-rule (ClaimOfferAtomV0 (uint256-rule) (int64-rule) (Asset-rule) (int64-rule) (Asset-rule) (int64-rule)))
   (ClaimAtomType-rule (choose (bv 1 (bitvector 32)) (bv 2 (bitvector 32)) (bv 0 (bitvector 32))))
   (ManageOfferSuccessResult-rule
    (ManageOfferSuccessResult
     (cons 1 (vector (ClaimAtom-rule)))
     (choose
      (cons (bv MANAGE_OFFER_UPDATED (bitvector 32)) (OfferEntry-rule))
      (cons (bv MANAGE_OFFER_DELETED (bitvector 32)) null)
      (cons (bv MANAGE_OFFER_CREATED (bitvector 32)) (OfferEntry-rule)))))
   (ManageBuyOfferResultCode-rule
    (choose
     (bv -12 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -11 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -9 (bitvector 32))
     (bv -10 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -1 (bitvector 32))))
   (ClaimClaimableBalanceResultCode-rule
    (choose
     (bv -3 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -1 (bitvector 32))))
   (EndSponsoringFutureReservesResultCode-rule (choose (bv -1 (bitvector 32)) (bv 0 (bitvector 32))))
   (BumpSequenceResultCode-rule (choose (bv -1 (bitvector 32)) (bv 0 (bitvector 32))))
   (SetTrustLineFlagsResultCode-rule
    (choose
     (bv -4 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -2 (bitvector 32))))
   (RevokeSponsorshipResultCode-rule
    (choose
     (bv -4 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -5 (bitvector 32))))
   (LiquidityPoolDepositResultCode-rule
    (choose
     (bv -3 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -7 (bitvector 32))))
   (PaymentResultCode-rule
    (choose
     (bv -4 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -9 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv 0 (bitvector 32))))
   (ClaimableBalanceIDType-rule (choose (bv 0 (bitvector 32))))
   (ClaimableBalanceID-rule (choose (cons (bv CLAIMABLE_BALANCE_ID_TYPE_V0 (bitvector 32)) (Hash-rule))))
   (CreateClaimableBalanceResultCode-rule
    (choose
     (bv -3 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv 0 (bitvector 32))))
   (SimplePaymentResult-rule (SimplePaymentResult (AccountID-rule) (Asset-rule) (int64-rule)))
   (PathPaymentStrictSendResultCode-rule
    (choose
     (bv 0 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -9 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv -10 (bitvector 32))
     (bv -12 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -11 (bitvector 32))))
   (ManageSellOfferResultCode-rule
    (choose
     (bv -9 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -12 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -10 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -11 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -6 (bitvector 32))))
   (ClawbackClaimableBalanceResultCode-rule
    (choose (bv -3 (bitvector 32)) (bv -2 (bitvector 32)) (bv -1 (bitvector 32)) (bv 0 (bitvector 32))))
   (ClawbackResultCode-rule
    (choose (bv -3 (bitvector 32)) (bv -2 (bitvector 32)) (bv 0 (bitvector 32)) (bv -4 (bitvector 32)) (bv -1 (bitvector 32))))
   (InflationPayout-rule (InflationPayout (AccountID-rule) (int64-rule)))
   (InflationResultCode-rule (choose (bv -1 (bitvector 32)) (bv 0 (bitvector 32))))
   (ChangeTrustResultCode-rule
    (choose
     (bv -1 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -5 (bitvector 32))))
   (ManageDataResultCode-rule
    (choose (bv -4 (bitvector 32)) (bv -2 (bitvector 32)) (bv -1 (bitvector 32)) (bv 0 (bitvector 32)) (bv -3 (bitvector 32))))
   (PathPaymentStrictReceiveResultCode-rule
    (choose
     (bv -2 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -9 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv -10 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -11 (bitvector 32))
     (bv -12 (bitvector 32))
     (bv -7 (bitvector 32))))
   (CreateAccountResultCode-rule
    (choose (bv -3 (bitvector 32)) (bv -1 (bitvector 32)) (bv 0 (bitvector 32)) (bv -2 (bitvector 32)) (bv -4 (bitvector 32))))
   (SetOptionsResultCode-rule
    (choose
     (bv -8 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -5 (bitvector 32))
     (bv -9 (bitvector 32))
     (bv -10 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -6 (bitvector 32))))
   (TransactionResultCode-rule
    (choose
     (bv -9 (bitvector 32))
     (bv -12 (bitvector 32))
     (bv -13 (bitvector 32))
     (bv -6 (bitvector 32))
     (bv -2 (bitvector 32))
     (bv -4 (bitvector 32))
     (bv -7 (bitvector 32))
     (bv -11 (bitvector 32))
     (bv -3 (bitvector 32))
     (bv -10 (bitvector 32))
     (bv -14 (bitvector 32))
     (bv 1 (bitvector 32))
     (bv -1 (bitvector 32))
     (bv -8 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv -5 (bitvector 32))))
   (InnerTransactionResultPair-rule (InnerTransactionResultPair (Hash-rule) (InnerTransactionResult-rule)))
   (OperationResult-rule
    (choose
     (cons (bv opTOO_MANY_SPONSORING (bitvector 32)) null)
     (cons
      (bv opINNER (bitvector 32))
      (choose
       (cons (bv CLAIM_CLAIMABLE_BALANCE (bitvector 32)) (ClaimClaimableBalanceResult-rule))
       (cons (bv MANAGE_BUY_OFFER (bitvector 32)) (ManageBuyOfferResult-rule))
       (cons (bv LIQUIDITY_POOL_WITHDRAW (bitvector 32)) (LiquidityPoolWithdrawResult-rule))
       (cons (bv BEGIN_SPONSORING_FUTURE_RESERVES (bitvector 32)) (BeginSponsoringFutureReservesResult-rule))
       (cons (bv ALLOW_TRUST (bitvector 32)) (AllowTrustResult-rule))
       (cons (bv ACCOUNT_MERGE (bitvector 32)) (AccountMergeResult-rule))
       (cons (bv SET_OPTIONS (bitvector 32)) (SetOptionsResult-rule))
       (cons (bv CREATE_ACCOUNT (bitvector 32)) (CreateAccountResult-rule))
       (cons (bv PATH_PAYMENT_STRICT_RECEIVE (bitvector 32)) (PathPaymentStrictReceiveResult-rule))
       (cons (bv MANAGE_DATA (bitvector 32)) (ManageDataResult-rule))
       (cons (bv CHANGE_TRUST (bitvector 32)) (ChangeTrustResult-rule))
       (cons (bv INFLATION (bitvector 32)) (InflationResult-rule))
       (cons (bv CLAWBACK (bitvector 32)) (ClawbackResult-rule))
       (cons (bv CLAWBACK_CLAIMABLE_BALANCE (bitvector 32)) (ClawbackClaimableBalanceResult-rule))
       (cons (bv CREATE_PASSIVE_SELL_OFFER (bitvector 32)) (ManageSellOfferResult-rule))
       (cons (bv MANAGE_SELL_OFFER (bitvector 32)) (ManageSellOfferResult-rule))
       (cons (bv PATH_PAYMENT_STRICT_SEND (bitvector 32)) (PathPaymentStrictSendResult-rule))
       (cons (bv LIQUIDITY_POOL_DEPOSIT (bitvector 32)) (LiquidityPoolDepositResult-rule))
       (cons (bv REVOKE_SPONSORSHIP (bitvector 32)) (RevokeSponsorshipResult-rule))
       (cons (bv SET_TRUST_LINE_FLAGS (bitvector 32)) (SetTrustLineFlagsResult-rule))
       (cons (bv CREATE_CLAIMABLE_BALANCE (bitvector 32)) (CreateClaimableBalanceResult-rule))
       (cons (bv PAYMENT (bitvector 32)) (PaymentResult-rule))
       (cons (bv BUMP_SEQUENCE (bitvector 32)) (BumpSequenceResult-rule))
       (cons (bv END_SPONSORING_FUTURE_RESERVES (bitvector 32)) (EndSponsoringFutureReservesResult-rule))))
     (cons (bv opEXCEEDED_WORK_LIMIT (bitvector 32)) null)
     (cons (bv opTOO_MANY_SUBENTRIES (bitvector 32)) null)
     (cons (bv opNOT_SUPPORTED (bitvector 32)) null)
     (cons (bv opNO_ACCOUNT (bitvector 32)) null)
     (cons (bv opBAD_AUTH (bitvector 32)) null)))
   (int64-rule (?? (bitvector 64)))))

; grammar for LedgerEntry: LedgerEntry-grammar
(begin
  (struct ClaimableBalanceEntryExtensionV1 (ext flags) #:transparent)
  (struct AccountEntry (accountID balance seqNum numSubEntries inflationDest flags homeDomain thresholds signers ext) #:transparent)
  (struct ext::TrustLineEntry::v1 (liabilities ext) #:transparent)
  (struct LiquidityPoolEntry (liquidityPoolID body) #:transparent)
  (struct TrustLineEntry (accountID asset balance limit flags ext) #:transparent)
  (struct LedgerEntry (lastModifiedLedgerSeq data ext) #:transparent)
  (struct ClaimableBalanceEntry (balanceID claimants asset amount ext) #:transparent)
  (struct LedgerEntryExtensionV1 (sponsoringID ext) #:transparent)
  (struct body::LiquidityPoolEntry::constantProduct (params reserveA reserveB totalPoolShares poolSharesTrustLineCount) #:transparent)
  (struct Liabilities (buying selling) #:transparent)
  (struct TrustLineEntryExtensionV2 (liquidityPoolUseCount ext) #:transparent)
  (struct DataEntry (accountID dataName dataValue ext) #:transparent)
  (struct AccountEntryExtensionV2 (numSponsored numSponsoring signerSponsoringIDs ext) #:transparent)
  (struct AccountEntryExtensionV1 (liabilities ext) #:transparent)
  (define-grammar
   (LedgerEntry-grammar)
   (LedgerEntry-rule
    (LedgerEntry
     (uint32-rule)
     (choose
      (cons (bv TRUSTLINE (bitvector 32)) (TrustLineEntry-rule))
      (cons (bv CLAIMABLE_BALANCE (bitvector 32)) (ClaimableBalanceEntry-rule))
      (cons (bv LIQUIDITY_POOL (bitvector 32)) (LiquidityPoolEntry-rule))
      (cons (bv DATA (bitvector 32)) (DataEntry-rule))
      (cons (bv OFFER (bitvector 32)) (OfferEntry-rule))
      (cons (bv ACCOUNT (bitvector 32)) (AccountEntry-rule)))
     (choose (cons (bv 0 (bitvector 32)) null) (cons (bv 1 (bitvector 32)) (LedgerEntryExtensionV1-rule)))))
   (Price-rule (Price (int32-rule) (int32-rule)))
   (SequenceNumber-rule (int64-rule))
   (string32-rule (cons (bv 2 32) (?? (bitvector 64))))
   (Thresholds-rule (?? (bitvector 32)))
   (Signer-rule (Signer (SignerKey-rule) (uint32-rule)))
   (AccountEntryExtensionV1-rule
    (AccountEntryExtensionV1
     (Liabilities-rule)
     (choose (cons (bv 0 (bitvector 32)) null) (cons (bv 2 (bitvector 32)) (AccountEntryExtensionV2-rule)))))
   (AccountEntryExtensionV2-rule
    (AccountEntryExtensionV2
     (uint32-rule)
     (uint32-rule)
     (cons 1 (vector (SponsorshipDescriptor-rule)))
     (choose (cons (bv 0 (bitvector 32)) null))))
   (SignerKeyType-rule (choose (bv 0 (bitvector 32)) (bv 1 (bitvector 32)) (bv 2 (bitvector 32))))
   (SignerKey-rule
    (choose
     (cons (bv SIGNER_KEY_TYPE_HASH_X (bitvector 32)) (uint256-rule))
     (cons (bv SIGNER_KEY_TYPE_ED25519 (bitvector 32)) (uint256-rule))
     (cons (bv SIGNER_KEY_TYPE_PRE_AUTH_TX (bitvector 32)) (uint256-rule))))
   (TrustLineAsset-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AlphaNum12-rule))
     (cons (bv ASSET_TYPE_NATIVE (bitvector 32)) null)
     (cons (bv ASSET_TYPE_POOL_SHARE (bitvector 32)) (PoolID-rule))
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AlphaNum4-rule))))
   (TrustLineEntryExtensionV2-rule (TrustLineEntryExtensionV2 (int32-rule) (choose (cons (bv 0 (bitvector 32)) null))))
   (Liabilities-rule (Liabilities (int64-rule) (int64-rule)))
   (ClaimableBalanceID-rule (choose (cons (bv CLAIMABLE_BALANCE_ID_TYPE_V0 (bitvector 32)) (Hash-rule))))
   (Claimant-rule (choose (cons (bv CLAIMANT_TYPE_V0 (bitvector 32)) (Claimant::v0 (AccountID-rule) (ClaimPredicate-rule)))))
   (ClaimableBalanceEntryExtensionV1-rule (ClaimableBalanceEntryExtensionV1 (choose (cons (bv 0 (bitvector 32)) null)) (uint32-rule)))
   (ClaimPredicateType-rule
    (choose
     (bv 2 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv 3 (bitvector 32))
     (bv 5 (bitvector 32))
     (bv 1 (bitvector 32))))
   (ClaimPredicate-rule
    (choose
     (cons (bv CLAIM_PREDICATE_UNCONDITIONAL (bitvector 32)) null)
     (cons
      (bv CLAIM_PREDICATE_NOT (bitvector 32))
      (choose (cons (bv TRUE (bitvector 32)) (ClaimPredicate-rule)) (cons (bv FALSE (bitvector 32)) null)))
     (cons (bv CLAIM_PREDICATE_BEFORE_RELATIVE_TIME (bitvector 32)) (int64-rule))
     (cons (bv CLAIM_PREDICATE_AND (bitvector 32)) (cons 1 (vector (ClaimPredicate-rule))))
     (cons (bv CLAIM_PREDICATE_OR (bitvector 32)) (cons 1 (vector (ClaimPredicate-rule))))
     (cons (bv CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME (bitvector 32)) (int64-rule))))
   (ClaimantType-rule (choose (bv 0 (bitvector 32))))
   (ClaimableBalanceIDType-rule (choose (bv 0 (bitvector 32))))
   (PoolID-rule (Hash-rule))
   (LiquidityPoolConstantProductParameters-rule (LiquidityPoolConstantProductParameters (Asset-rule) (Asset-rule) (int32-rule)))
   (int64-rule (?? (bitvector 64)))
   (LiquidityPoolType-rule (choose (bv 0 (bitvector 32))))
   (AssetType-rule (choose (bv 3 (bitvector 32)) (bv 1 (bitvector 32)) (bv 2 (bitvector 32)) (bv 0 (bitvector 32))))
   (AlphaNum4-rule (AlphaNum4 (AssetCode4-rule) (AccountID-rule)))
   (AlphaNum12-rule (AlphaNum12 (AssetCode12-rule) (AccountID-rule)))
   (AssetCode12-rule (?? (bitvector 96)))
   (AssetCode4-rule (?? (bitvector 32)))
   (int32-rule (?? (bitvector 32)))
   (Asset-rule
    (choose
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM12 (bitvector 32)) (AlphaNum12-rule))
     (cons (bv ASSET_TYPE_NATIVE (bitvector 32)) null)
     (cons (bv ASSET_TYPE_CREDIT_ALPHANUM4 (bitvector 32)) (AlphaNum4-rule))))
   (Hash-rule (?? (bitvector 256)))
   (string64-rule (cons (bv 2 32) (?? (bitvector 64))))
   (DataValue-rule (cons 64 (?? (bitvector 512))))
   (SponsorshipDescriptor-rule (choose (cons (bv TRUE (bitvector 32)) (AccountID-rule)) (cons (bv FALSE (bitvector 32)) null)))
   (PublicKey-rule (choose (cons (bv PUBLIC_KEY_TYPE_ED25519 (bitvector 32)) (uint256-rule))))
   (uint256-rule (?? (bitvector 256)))
   (PublicKeyType-rule (choose (bv 0 (bitvector 32))))
   (AccountID-rule (PublicKey-rule))
   (bool-rule (choose (bv 1 (bitvector 32)) (bv 0 (bitvector 32))))
   (LedgerEntryExtensionV1-rule (LedgerEntryExtensionV1 (SponsorshipDescriptor-rule) (choose (cons (bv 0 (bitvector 32)) null))))
   (LedgerEntryType-rule
    (choose
     (bv 2 (bitvector 32))
     (bv 0 (bitvector 32))
     (bv 1 (bitvector 32))
     (bv 4 (bitvector 32))
     (bv 5 (bitvector 32))
     (bv 3 (bitvector 32))))
   (DataEntry-rule (DataEntry (AccountID-rule) (string64-rule) (DataValue-rule) (choose (cons (bv 0 (bitvector 32)) null))))
   (LiquidityPoolEntry-rule
    (LiquidityPoolEntry
     (PoolID-rule)
     (choose
      (cons
       (bv LIQUIDITY_POOL_CONSTANT_PRODUCT (bitvector 32))
       (body::LiquidityPoolEntry::constantProduct
        (LiquidityPoolConstantProductParameters-rule)
        (int64-rule)
        (int64-rule)
        (int64-rule)
        (int64-rule))))))
   (ClaimableBalanceEntry-rule
    (ClaimableBalanceEntry
     (ClaimableBalanceID-rule)
     (cons 1 (vector (Claimant-rule)))
     (Asset-rule)
     (int64-rule)
     (choose (cons (bv 0 (bitvector 32)) null) (cons (bv 1 (bitvector 32)) (ClaimableBalanceEntryExtensionV1-rule)))))
   (TrustLineEntry-rule
    (TrustLineEntry
     (AccountID-rule)
     (TrustLineAsset-rule)
     (int64-rule)
     (int64-rule)
     (uint32-rule)
     (choose
      (cons (bv 0 (bitvector 32)) null)
      (cons
       (bv 1 (bitvector 32))
       (ext::TrustLineEntry::v1
        (Liabilities-rule)
        (choose (cons (bv 0 (bitvector 32)) null) (cons (bv 2 (bitvector 32)) (TrustLineEntryExtensionV2-rule))))))))
   (AccountEntry-rule
    (AccountEntry
     (AccountID-rule)
     (int64-rule)
     (SequenceNumber-rule)
     (uint32-rule)
     (choose (cons (bv TRUE (bitvector 32)) (AccountID-rule)) (cons (bv FALSE (bitvector 32)) null))
     (uint32-rule)
     (string32-rule)
     (Thresholds-rule)
     (cons 1 (vector (Signer-rule)))
     (choose (cons (bv 0 (bitvector 32)) null) (cons (bv 1 (bitvector 32)) (AccountEntryExtensionV1-rule)))))
   (OfferEntry-rule
    (OfferEntry
     (AccountID-rule)
     (int64-rule)
     (Asset-rule)
     (Asset-rule)
     (int64-rule)
     (Price-rule)
     (uint32-rule)
     (choose (cons (bv 0 (bitvector 32)) null))))
   (uint32-rule (?? (bitvector 32)))))